version: '3.8'

services:
  yelb-ui:
    container_name: yelb-ui
    image: mreferre/yelb-ui:0.7
    ports:
      - "80:80"
    depends_on:
      - yelb-appserver
    networks:
      - odilia

  yelb-appserver:
    container_name: yelb-appserver
    image: mreferre/yelb-appserver:0.5
    ports:
      - "3000:3000"
    depends_on:
      - redis-server
      - yelb-db
    networks:
      - odilia

  yelb-db:
    container_name: yelb-db
    image: mreferre/yelb-db:0.5
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - odilia
  
  odilia-db-replication01:
    container_name: odilia-db-replication01
    image: mreferre/yelb-db:0.5
    volumes:
      - db_data01:/var/lib/postgresql/data
    networks:
      - odilia
    depends_on:
      - yelb-db
  
  odilia-db-replication02:
    container_name: odilia-db-replication02
    image: mreferre/yelb-db:0.5
    volumes:
      - db_data02:/var/lib/postgresql/data
    networks:
      - odilia
    depends_on:
      - yelb-db
  
  odilia-db-replication03:
    container_name: odilia-db-replication03
    image: mreferre/yelb-db:0.5
    volumes:
      - db_data03:/var/lib/postgresql/data
    networks:
      - odilia
    depends_on:
      - yelb-db

  redis-server:
    container_name: redis-server
    image: redis:4.0.2
    volumes: 
      - db_data0:/data
    networks:
      - odilia

  odilia-redis01:
    container_name: odilia-redis01
    image: redis:4.0.2
    volumes: 
      - db_data04:/data
    networks:
      - odilia
    depends_on:
      - redis-server
  
  odilia-redis02:
    container_name: odilia-redis02
    image: redis:4.0.2
    volumes: 
      - db_data05:/data
    networks:
      - odilia
    depends_on:
      - redis-server
  
  odilia-redis-sentinel01:
    container_name: odilia-redis-sentinel01
    image: redis:4.0.2
    volumes:
      - db_data06:/data
    networks: 
      - odilia
    depends_on:
      - redis-server
  
  odilia-redis-sentinel02:
    container_name: odilia-redis-sentinel02
    image: redis:4.0.2
    volumes:
      - db_data07:/data
    networks: 
      - odilia
    depends_on:
      - odilia-redis-sentinel01

  odilia-redis-sentinel03:
    container_name: odilia-redis-sentinel03
    image: redis:4.0.2
    volumes:
      - db_data08:/data
    networks: 
      - odilia
    depends_on:
      - odilia-redis-sentinel01

volumes:
  db_data:
  db_data0:
  db_data01:
  db_data02:
  db_data03:
  db_data04:
  db_data05:
  db_data06:
  db_data07:
  db_data08:

networks:
  odilia:
  
